version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${PHP_XDEBUG-./config/php/xdebug.ini}:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  mysql:
    build:
      context: "./bin/${DATABASE}"
    container_name: 'mysql'
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  elastic:
    # docker pull docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    # sysctl -w vm.max_map_count=262144
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    environment: 
      - discovery.type=single-node
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
      - 9300:9300
    links: 
      - kibana      

  kibana:
    image: kibana:7.3.2
    restart: always
    environment: 
      - "ELASTICSEARCH_HOSTS=http://magento.kibana:9200"
      - XPACK_GRAPH_ENABLED=true
      - XPACK_WATCHER_ENABLED=true
      - XPACK_ML_ENABLED=true
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
    ports:
      - 5601:5601